<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

 
  <ItemGroup>
	<Compile Remove="Templates\**\*.cs" />
	<None Include="Templates\**\*.*">
		<CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</None>
  </ItemGroup>

 
  <ItemGroup>
    <PackageReference Include="Spectre.Console" Version="0.54.0" />
    <PackageReference Include="Spectre.Console.Cli" Version="0.53.1" />
  </ItemGroup>

 
  <ItemGroup>
    <Folder Include="Templates\appsettings\" />
  </ItemGroup>


</Project>
